#!/bin/bash

IFS=/ command eval 'read -ra GITHUB_PATH <<< "$1"'

if [[ ${#GITHUB_PATH[@]} != 2 ]]; then
    echo "Wrong format for github path." >&2
    show_error_usage
    exit 1
fi

GITHUB_USER="${GITHUB_PATH[0]}"
GITHUB_PROJECT="${GITHUB_PATH[1]}"
URL=https://github.com/$GITHUB_USER/$GITHUB_PROJECT/releases/latest

function error
{
    echo "Error: $1" >&2
}

function check_project_url_exists
{
    local http_code
    http_code=$(curl -L -s -o /dev/null -w "%{http_code}" "$URL")
    if [ "$http_code" -lt "200" ] || [ "$http_code" -gt "299" ]; then
        error "page error for <$URL>, $http_code"
        echo >&2
        >&2 curl -L -i "$URL" 2>/dev/null
        exit 1
    fi
}
check_project_url_exists

PRJ_VER=$(curl -L -s "$URL" 2>&1 | grep -oE releases\/tag\/\[v\]?\[0-9\]+\.\[0-9\]+\.\[0-9\]+ | head -n 1 | grep -oE \[0-9\]+\.\[0-9\]+\.\[0-9\]+)
echo -n "$PRJ_VER"
